name: Bug Report
description: Report a bug in the simulator (something that should work but doesn't)
title: "[BUG]: "
labels: ["bug", "documentation", "duplicate", "enhancement", "good first issue", "help wanted", "invalid", "question", "wontfix", ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please provide enough detail that someone else can reproduce it.

        *"If you tell me 'it doesn't work', I will send you to explain it to the Archchancellor. Be specific."*

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What went wrong? Be specific.
      placeholder: "The Modbus TCP server crashes when reading holding register 42..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What should have happened?
      placeholder: "Should return the register value without crashing..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can someone else trigger this bug?
      placeholder: |
        1. Start simulator with default config
        2. Run: mbtget -r -a 42 -n 1 localhost:[portnumber]
        3. Observe crash
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include error messages, stack traces, or relevant log output
      placeholder: |
        Paste logs here (check logs/ directory or console output)
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What system are you running on?
      value: |
        - OS: [e.g., Ubuntu 24.04, macOS 14.0]
        - Python version: [e.g., 3.12.3]
        - Simulator version: [e.g., commit hash or branch]
        - Installation method: [e.g., git clone, pip install]
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Any non-standard configuration? (Modified YAML files, custom devices, etc.)
      placeholder: "Using custom network topology in config/network.yml..."

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How severe is this bug?
      options:
        - Critical (simulator won't start or crashes immediately)
        - High (major feature broken)
        - Medium (feature works but with issues)
        - Low (minor issue or cosmetic)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Before submitting, verify these items
      options:
        - label: I searched existing issues and this isn't a duplicate
          required: true
        - label: I'm using the latest version from the main branch
          required: true
        - label: I've included enough detail to reproduce the bug
          required: true
        - label: I've checked logs/ directory for relevant error messages
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else relevant? Screenshots, related issues, potential causes?
