name: Security Vulnerability
description: Report a security issue in the simulator itself (not simulated vulnerabilities)
title: "[SECURITY]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Private Reporting Recommended

        If this is a **serious security vulnerability** (remote code execution, credential exposure, etc.), please use GitHub's [private security advisory feature](https://github.com/tymyrddin/power-and-light-sim/security/advisories/new) instead of this public issue.

        For **coordinated disclosure** or **sensitive vulnerabilities**, contact directly: https://tymyrddin.dev/contact/

        ---

        *"Security through obscurity is not security. But neither is publicly announcing vulnerabilities before they're fixed."*

        ---

        This template is for:
        - Lower-severity issues (information disclosure, DoS, etc.)
        - Simulated vulnerabilities that are unintentionally exploitable
        - Security design flaws in the simulator architecture

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: How severe is this vulnerability?
      options:
        - Critical (RCE, credential theft, system compromise)
        - High (privilege escalation, authentication bypass)
        - Medium (information disclosure, DoS)
        - Low (minor information leak, theoretical issue)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: What is the security issue?
      placeholder: "The Modbus TCP server accepts arbitrary writes without authentication, allowing remote attackers to..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Type
      description: What kind of security issue is this?
      options:
        - Unintended attack surface (simulator itself vulnerable)
        - Simulated vulnerability that's actually exploitable
        - Authentication or authorisation bypass
        - Credential exposure or insecure storage
        - Code injection or command execution
        - Denial of service
        - Information disclosure
        - Security design flaw
        - Other (describe below)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Attack Impact
      description: What can an attacker do with this vulnerability?
      placeholder: |
        Attacker can:
        - Execute arbitrary Python code on the host
        - Read sensitive files from the simulator host
        - Cause simulator crash (DoS)
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: How to exploit this vulnerability? (Proof of concept)
      placeholder: |
        1. Start simulator with default config
        2. Send malicious Modbus packet: [packet details]
        3. Observe code execution or file access
      render: shell
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept Code
      description: If you have exploit code, include it here (within reason)
      placeholder: |
        ```python
        # PoC exploit code
        import socket
        # ... (simplified for demonstration)
        ```
      render: python

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which parts of the simulator are affected?
      placeholder: |
        - components/network/servers/modbus_tcp_server.py (lines 123-145)
        - components/protocols/modbus/modbus_tcp_adapter.py
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How should this be fixed?
      placeholder: |
        - Add input validation in ModbusTCPServer._handle_write()
        - Implement authentication before accepting writes
        - Sanitise user-supplied data before processing

  - type: checkboxes
    id: disclosure
    attributes:
      label: Coordinated Disclosure
      description: Have you followed responsible disclosure practices?
      options:
        - label: I reported this privately first (via security advisory or email)
        - label: This is a public report of a low-severity issue
        - label: I'm willing to wait for a patch before public disclosure
        - label: I've verified this is a real vulnerability, not expected simulator behaviour

  - type: textarea
    id: timeline
    attributes:
      label: Disclosure Timeline
      description: When do you plan to disclose this publicly? (90 days is standard)
      placeholder: "Planning to disclose 90 days from report date, or when patch is released, whichever comes first"

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to similar vulnerabilities, CVEs, security research, or documentation
      placeholder: |
        - Similar issue in other simulators: [link]
        - Related CVE: CVE-XXXX-XXXXX
        - Security research paper: [link]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else relevant? Testing environment, discovered during research, etc.